Traceback (most recent call last):
  File "/home/vivs/.local/lib/python3.10/site-packages/concrete/fhe/compilation/compiler.py", line 434, in compile
    self._evaluate("Compiling", inputset)
  File "/home/vivs/.local/lib/python3.10/site-packages/concrete/fhe/compilation/compiler.py", line 279, in _evaluate
    self._trace(first_sample)
  File "/home/vivs/.local/lib/python3.10/site-packages/concrete/fhe/compilation/compiler.py", line 207, in _trace
    self.graph = Tracer.trace(self.function, parameters)
  File "/home/vivs/.local/lib/python3.10/site-packages/concrete/fhe/tracing/tracer.py", line 77, in trace
    output_tracers: Any = function(**arguments)
  File "/home/vivs/.local/lib/python3.10/site-packages/concrete/ml/sklearn/base.py", line 1541, in inference_to_compile
    return self._inference(q_X)
  File "/home/vivs/.local/lib/python3.10/site-packages/concrete/ml/sklearn/base.py", line 1552, in _inference
    y_pred = q_X @ self._q_weights - self._weight_quantizer.zero_point * numpy.sum(
  File "/home/vivs/.local/lib/python3.10/site-packages/concrete/fhe/tracing/tracer.py", line 517, in __matmul__
    return Tracer._trace_numpy_operation(np.matmul, self, self.sanitize(other))
  File "/home/vivs/.local/lib/python3.10/site-packages/concrete/fhe/tracing/tracer.py", line 403, in _trace_numpy_operation
    evaluation = operation(*sample, **kwargs)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 512 is different from 20)
